### Research Question: Which US University Produced the Best Players in Each Position in the 2014-2015 Season?

In [1]:
import pandas as pd
import pandas_profiling
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Step #1 - Load our data and remove any n/a values

In [31]:
players_stats_og = (
pd.read_csv('/Users/Nick/Desktop/Final Project/data/raw/players_stats.csv')
.dropna()
.reset_index()
.drop(['index'], axis = 1)
.rename(columns={"Collage" : "College", "Pos" : "Position"})
)

players_stats_og

,Name,Games Played,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,...,Age,Birth_Place,Birthdate,College,Experience,Height,Position,Team,Weight,BMI
0,AJ Price,26,324,133,51,137,37.2,15,57,26.3,...,29.0,us,"October 7, 1986",University of Connecticut,5,185.0,PG,PHO,81.45,23.798393
1,Aaron Brooks,82,1885,954,344,817,42.1,121,313,38.7,...,30.0,us,"January 14, 1985",University of Oregon,6,180.0,PG,CHI,72.45,22.361111
2,Aaron Gordon,47,797,243,93,208,44.7,13,48,27.1,...,20.0,us,"September 16, 1995",University of Arizona,R,202.5,PF,ORL,99.00,24.142661
3,Adreian Payne,32,740,213,91,220,41.4,1,9,11.1,...,24.0,us,"February 19, 1991",Michigan State University,R,205.0,PF,ATL,106.65,25.377751
4,Al Horford,76,2318,1156,519,965,53.8,11,36,30.6,...,29.0,do,"June 3, 1986",University of Florida,7,205.0,C,ATL,110.25,26.234384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,Willie Green,52,951,306,118,306,38.6,42,121,34.7,...,34.0,us,"July 28, 1981",University of Detroit Mercy,11,190.0,SG,ORL,90.00,24.930748
346,Wilson Chandler,78,2471,1085,418,975,42.9,139,406,34.2,...,28.0,us,"May 10, 1987",DePaul University,7,200.0,SF,DEN,101.25,25.312500
347,Xavier Henry,9,86,20,3,13,23.1,0,0,0.0,...,24.0,be,"March 15, 1991",University of Kansas,4,195.0,SF,LAL,99.00,26.035503
348,Zach LaVine,77,1902,778,286,677,42.2,57,167,34.1,...,20.0,us,"March 10, 1995","University of California, Los Angeles",R,192.5,PG,MIN,85.05,22.951594
349,Zach Randolph,71,2304,1143,454,932,48.7,7,20,35.0,...,34.0,us,"July 16, 1981",Michigan State University,13,202.5,PF,MEM,117.00,28.532236

In [58]:
players_stats_university = (
        players_stats_og[players_stats_og['College'].notnull()]
        .reset_index()
        .drop(columns=['index','Age','Games Played', 'MIN', 'Birthdate','Birth_Place', 'Experience', 'Height', 'Team', 'Weight', 'BMI']) 
        )

In [59]:
players_stats_PG = (
        players_stats_university.loc[players_stats_university['Position'] == 'PG']
        .sort_values(by = 'EFF', ascending=False)
        .reset_index()
        .drop(columns=['index'])
        )
    
players_stats_SG = (
        players_stats_university.loc[players_stats_university['Position'] == 'SG']
        .sort_values(by = 'EFF', ascending=False)
        .reset_index()
        .drop(columns=['index'])
        )

players_stats_SF = (
        players_stats_university.loc[players_stats_university['Position'] == 'SF']
        .sort_values(by = 'EFF', ascending=False)
        .reset_index()
        .drop(columns=['index'])
        )

players_stats_PF = (
        players_stats_university.loc[players_stats_university['Position'] == 'PF']
        .sort_values(by = 'EFF', ascending=False)
        .reset_index()
        .drop(columns=['index'])
        )

players_stats_C = (
        players_stats_university.loc[players_stats_university['Position'] == 'C']
        .sort_values(by = 'EFF', ascending=False)
        .reset_index()
        .drop(columns=['index'])
        )

In [61]:
# Point Gaurd Analysis + Visualizations

players_stats_PG

,Name,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,AST,STL,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,College,Position
0,Chris Paul,1564,568,1170,48.5,139,349,39.8,289,321,...,838,156,15,190,203,2125,4.41,0.82,Wake Forest University,PG
1,Stephen Curry,1900,653,1341,48.7,286,646,44.3,308,337,...,619,163,16,249,158,2073,2.49,0.66,Davidson College,PG
2,Damian Lillard,1720,590,1360,43.4,196,572,34.3,344,398,...,507,97,21,222,164,1677,2.28,0.44,Weber State University,PG
3,Eric Bledsoe,1377,468,1046,44.7,88,272,32.4,353,441,...,493,127,45,274,189,1525,1.80,0.46,University of Kentucky,PG
4,Kyrie Irving,1628,578,1235,46.8,157,378,41.5,315,365,...,389,114,20,186,146,1495,2.09,0.61,Duke University,PG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,David Stockton,8,2,6,33.3,1,2,50.0,3,6,...,9,2,0,4,1,10,2.25,0.50,Gonzaga University,PG
73,Jerel McNeal,9,3,11,27.3,1,2,50.0,2,2,...,2,3,1,5,5,5,0.40,0.60,Marquette University,PG
74,Gal Mekel,6,3,20,15.0,0,3,0.0,0,0,...,13,2,0,2,1,3,6.50,1.00,Wichita State University,PG
75,Seth Curry,0,0,3,0.0,0,1,0.0,0,0,...,1,0,0,0,2,0,0.00,0.00,Duke University,PG
76,Kalin Lucas,0,0,1,0.0,0,0,0.0,0,0,...,0,1,0,0,1,0,0.00,0.00,Michigan State University,PG

In [62]:
# Shooting Gaurd Analysis + Visualizations

players_stats_SG

,Name,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,AST,STL,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,College,Position
0,James Harden,2217,647,1470,44.0,208,555,37.5,715,824,...,565,154,60,321,208,2202,1.76,0.48,Arizona State University,SG
1,Tyreke Evans,1313,521,1165,44.7,69,227,30.4,202,291,...,521,100,37,246,198,1408,2.12,0.41,University of Memphis,SG
2,Klay Thompson,1668,602,1299,46.3,239,545,43.9,225,256,...,222,87,60,149,122,1407,1.49,0.58,Washington State University,SG
3,Jimmy Butler,1301,421,912,46.2,73,193,37.8,386,463,...,212,114,36,93,108,1381,2.28,1.23,Marquette University,SG
4,Victor Oladipo,1292,473,1086,43.6,84,248,33.9,262,320,...,295,120,19,204,187,1153,1.45,0.59,Indiana University,SG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,Jamaal Franklin,3,1,2,50.0,1,2,50.0,0,0,...,3,0,1,3,4,5,1.00,0.00,San Diego State University,SG
80,Patrick Christopher,6,3,12,25.0,0,4,0.0,0,0,...,0,1,0,1,6,3,0.00,1.00,University of California,SG
81,Toure' Murry,6,2,5,40.0,0,0,0.0,2,2,...,1,1,0,4,2,2,0.25,0.25,Wichita State University,SG
82,Glen Rice,11,3,15,20.0,1,7,14.3,4,6,...,2,0,0,2,11,1,1.00,0.00,Georgia Institute of Technology,SG
83,Andre Dawkins,3,1,6,16.7,1,6,16.7,0,0,...,1,0,0,1,3,0,1.00,0.00,Duke University,SG

In [63]:
# Small Forward Analysis + Visualizations

players_stats_SF

,Name,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,AST,STL,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,College,Position
0,Gordon Hayward,1463,484,1087,44.5,120,330,36.4,375,462,...,313,108,30,206,131,1391,1.52,0.52,Butler University,SF
1,Rudy Gay,1432,508,1116,45.5,79,220,35.9,337,393,...,250,71,41,183,157,1346,1.37,0.39,University of Connecticut,SF
2,Kawhi Leonard,1057,394,822,47.9,67,192,34.9,202,252,...,161,148,48,97,128,1300,1.66,1.53,San Diego State University,SF
3,Trevor Ariza,1048,366,910,40.2,194,555,35.0,122,143,...,209,152,17,141,186,1179,1.48,1.08,"University of California, Los Angeles",SF
4,Tobias Harris,1164,442,949,46.6,87,239,36.4,193,245,...,124,69,36,115,134,1149,1.08,0.60,University of Tennessee,SF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Francisco Garcia,45,17,63,27.0,10,45,22.2,1,4,...,15,9,5,10,20,32,1.50,0.90,University of Louisville,SF
60,Cartier Martin,36,15,53,28.3,6,33,18.2,0,0,...,11,3,1,5,20,28,2.20,0.60,Kansas State University,SF
61,Dahntay Jones,21,6,21,28.6,0,4,0.0,9,11,...,2,3,0,1,23,19,2.00,3.00,Duke University,SF
62,Xavier Henry,20,3,13,23.1,0,0,0.0,14,24,...,3,3,0,3,6,7,1.00,1.00,University of Kansas,SF
63,Darius Miller,2,1,7,14.3,0,1,0.0,0,0,...,2,1,0,1,8,-1,2.00,1.00,University of Kentucky,SF

In [64]:
# Power Forward Analysis + Visualizations

players_stats_PF

,Name,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,AST,STL,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,College,Position
0,Anthony Davis,1656,642,1199,53.5,1,12,8.3,371,461,...,149,100,200,95,141,2059,1.57,1.05,University of Kentucky,PF
1,LaMarcus Aldridge,1661,659,1415,46.6,37,105,35.2,306,362,...,124,48,68,122,125,1693,1.02,0.39,University of Texas at Austin,PF
2,Blake Griffin,1469,574,1144,50.2,10,25,40.0,311,427,...,354,63,35,152,196,1591,2.33,0.41,University of Oklahoma,PF
3,Kevin Love,1228,413,952,43.4,144,392,36.7,258,321,...,168,51,39,122,140,1493,1.38,0.42,"University of California, Los Angeles",PF
4,Paul Millsap,1218,443,930,47.6,77,216,35.6,255,337,...,223,130,69,166,201,1475,1.34,0.78,Louisiana Tech University,PF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Drew Gordon,17,8,19,42.1,0,3,0.0,1,2,...,2,1,0,8,7,18,0.25,0.13,University of New Mexico,PF
72,Grant Jerrett,16,7,26,26.9,1,15,6.7,1,1,...,3,2,2,3,11,10,1.00,0.67,University of Arizona,PF
73,Cameron Bairstow,10,3,14,21.4,0,0,0.0,4,5,...,1,2,1,3,8,7,0.33,0.67,University of New Mexico,PF
74,Jerrelle Benimon,0,0,0,0.0,0,0,0.0,0,0,...,0,0,0,1,0,2,0.00,0.00,Towson University,PF
75,Julius Randle,2,1,3,33.3,0,0,0.0,0,2,...,0,0,0,1,1,-3,0.00,0.00,University of Kentucky,PF

In [65]:
# Center Analysis + Visualizations

players_stats_C

,Name,PTS,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,...,AST,STL,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,College,Position
0,DeAndre Jordan,946,379,534,71.0,1,4,25.0,187,471,...,61,81,183,109,245,1949,0.56,0.74,Texas A&M University,C
1,Nikola Vucevic,1428,631,1206,52.3,2,6,33.3,164,218,...,147,54,54,148,220,1716,0.99,0.37,University of Southern California,C
2,Andre Drummond,1130,494,961,51.4,0,2,0.0,142,365,...,55,73,153,120,285,1705,0.46,0.61,University of Connecticut,C
3,DeMarcus Cousins,1421,498,1066,46.7,2,8,25.0,423,541,...,210,90,103,254,241,1631,0.83,0.35,University of Kentucky,C
4,Tim Duncan,1070,419,819,51.2,2,7,28.6,230,311,...,230,63,151,131,165,1606,1.76,0.48,Wake Forest University,C
5,Al Horford,1156,519,965,53.8,11,36,30.6,107,141,...,244,68,98,100,121,1530,2.44,0.68,University of Florida,C
6,Brook Lopez,1236,506,987,51.3,1,10,10.0,223,274,...,50,43,126,104,206,1354,0.48,0.41,Stanford University,C
7,Gorgui Dieng,710,259,512,50.6,1,6,16.7,191,244,...,146,71,126,126,188,1230,1.16,0.56,University of Louisville,C
8,Nerlens Noel,744,302,653,46.2,0,0,0.0,140,230,...,128,133,142,146,208,1171,0.88,0.91,University of Kentucky,C
9,Joakim Noah,485,190,427,44.5,0,2,0.0,105,174,...,312,48,74,123,203,1136,2.54,0.39,University of Florida,C
10,Evan Turner,779,320,746,42.9,33,119,27.7,106,141,...,449,83,19,198,180,1088,2.27,0.42,Vanderbilt University,C
11,Roy Hibbert,802,317,710,44.6,0,2,0.0,168,204,...,84,18,125,107,216,1033,0.79,0.17,Georgetown University,C
12,Jordan Hill,841,357,777,45.9,3,11,27.3,124,168,...,103,34,52,106,164,1016,0.97,0.32,University of Arizona,C
13,Andrew Bogut,422,200,355,56.3,0,0,0.0,22,42,...,180,39,113,106,188,1016,1.70,0.37,University of Utah,C
14,Mason Plumlee,717,280,489,57.3,0,3,0.0,157,317,...,74,65,63,106,207,956,0.70,0.61,Duke University,C
15,Steven Adams,537,217,399,54.4,0,2,0.0,103,205,...,66,38,86,99,222,867,0.67,0.38,University of Pittsburgh,C
16,Chris Kaman,638,283,549,51.5,0,0,0.0,72,102,...,65,18,54,108,140,855,0.60,0.17,Central Michigan University,C
17,Chris Bosh,928,343,745,46.0,63,168,37.5,179,232,...,95,41,25,95,69,849,1.00,0.43,Georgia Institute of Technology,C
18,Robin Lopez,566,234,437,53.5,0,1,0.0,98,127,...,55,16,84,73,122,810,0.75,0.22,Stanford University,C
19,Marreese Speights,791,318,646,49.2,5,18,27.8,150,178,...,72,20,34,82,189,804,0.88,0.24,University of Florida,C
20,Alex Len,432,179,353,50.7,1,3,33.3,73,104,...,32,34,105,74,213,778,0.43,0.46,University of Maryland,C
21,Kelly Olynyk,656,251,528,47.5,61,175,34.9,93,136,...,109,64,39,98,213,753,1.11,0.65,Gonzaga University,C
22,JJ Hickson,552,218,459,47.5,0,2,0.0,116,201,...,57,36,35,96,136,710,0.59,0.38,North Carolina State University,C
23,John Henson,470,196,346,56.6,0,0,0.0,78,137,...,59,28,135,87,152,708,0.68,0.32,University of North Carolina,C
24,Kosta Koufos,419,182,358,50.8,0,0,0.0,55,85,...,37,29,63,69,148,699,0.54,0.42,Ohio State University,C
25,Aron Baynes,461,185,327,56.6,1,4,25.0,90,104,...,35,16,22,65,162,631,0.54,0.25,Washington State University,C
26,Cole Aldrich,338,144,301,47.8,0,0,0.0,50,64,...,75,37,65,59,122,623,1.27,0.63,University of Kansas,C
27,Tarik Black,379,157,273,57.5,0,1,0.0,65,118,...,42,19,24,48,158,615,0.88,0.40,University of Kansas,C
28,Chris Andersen,320,120,207,58.0,4,13,30.8,76,114,...,43,26,61,40,88,584,1.08,0.65,Blinn College,C
29,Miles Plumlee,294,136,254,53.5,0,0,0.0,22,46,...,34,41,66,51,111,562,0.67,0.80,Duke University,C
30,Lavoy Allen,315,141,299,47.2,0,0,0.0,33,47,...,73,15,42,40,102,556,1.83,0.38,Temple University,C
31,Meyers Leonard,327,125,245,51.0,47,112,42.0,30,32,...,32,10,14,39,113,472,0.82,0.26,University of Illinois at Urbana-Champaign,C
32,Dewayne Dedmon,216,91,162,56.2,0,1,0.0,34,64,...,9,16,50,51,141,434,0.18,0.31,University of Southern California,C
33,Justin Hamilton,219,85,178,47.8,10,31,32.3,39,47,...,36,27,30,26,70,319,1.39,1.04,Louisiana State University,C
34,Samuel Dalembert,128,57,130,43.8,0,0,0.0,14,20,...,29,14,41,39,70,262,0.74,0.36,Seton Hall University,C
35,Jerome Jordan,138,50,94,53.2,0,0,0.0,38,44,...,13,8,15,22,58,207,0.59,0.36,University of Tulsa,C
36,Ryan Hollins,137,53,82,64.6,0,0,0.0,31,54,...,14,6,19,25,65,202,0.56,0.24,"University of California, Los Angeles",C
37,Joel Anthony,87,36,62,58.1,0,0,0.0,15,22,...,5,12,49,12,55,201,0.42,1.00,"University of Nevada, Las Vegas",C
38,Elton Brand,96,42,95,44.2,0,1,0.0,12,23,...,22,17,25,18,54,178,1.22,0.94,Duke University,C
39,JaVale McGee,106,42,79,53.2,0,0,0.0,22,33,...,3,2,20,18,30,126,0.17,0.11,"University of Nevada, Reno",C
40,Chuck Hayes,50,22,46,47.8,0,0,0.0,6,11,...,20,10,4,8,37,98,2.50,1.25,University of Kentucky,C
41,Bernard James,44,12,27,44.4,0,0,0.0,20,23,...,4,2,15,6,17,80,0.67,0.33,Florida State University,C
42,Nazr Mohammed,27,13,30,43.3,0,0,0.0,1,3,...,3,4,5,7,16,51,0.43,0.57,University of Kentucky,C
43,Arinze Onuaku,27,12,14,85.7,0,0,0.0,3,8,...,4,1,3,2,6,47,2.00,0.50,Syracuse University,C
44,Brendan Haywood,35,14,30,46.7,0,0,0.0,7,13,...,2,2,10,10,17,46,0.20,0.20,University of North Carolina,C
45,Earl Barron,32,12,39,30.8,2,4,50.0,6,12,...,5,4,2,5,26,33,1.00,0.80,University of Memphis,C
46,Greg Stiemsma,14,6,8,75.0,0,0,0.0,2,4,...,3,2,0,7,15,23,0.43,0.29,University of Wisconsin,C
47,Sim Bhullar,2,1,2,50.0,0,0,0.0,0,0,...,1,0,1,0,0,4,0.00,0.00,New Mexico State University,C
48,Alex Kirk,4,1,4,25.0,0,0,0.0,2,2,...,1,0,0,0,1,3,0.00,0.00,University of New Mexico,C