In [2]:
import pandas as pd

In [16]:
df = pd.read_csv('../../data/raw/players_stats.csv')
df1 = df.drop(columns = ['BMI','Weight','Team','Birth_Place','Birthdate','Age'])
df2 = df1['Experience'].str.replace('R','0')
df1['Experience'] = df2
df1

,Name,Games Played,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,...,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,Collage,Experience,Height,Pos
0,AJ Price,26,324,133,51,137,37.2,15,57,26.3,...,0,14,15,110,3.29,0.50,University of Connecticut,5,185.0,PG
1,Aaron Brooks,82,1885,954,344,817,42.1,121,313,38.7,...,15,157,189,791,1.66,0.34,University of Oregon,6,180.0,PG
2,Aaron Gordon,47,797,243,93,208,44.7,13,48,27.1,...,22,38,83,318,0.87,0.55,University of Arizona,0,202.5,PF
3,Adreian Payne,32,740,213,91,220,41.4,1,9,11.1,...,9,44,88,244,0.68,0.43,Michigan State University,0,205.0,PF
4,Al Horford,76,2318,1156,519,965,53.8,11,36,30.6,...,98,100,121,1530,2.44,0.68,University of Florida,7,205.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,Xavier Henry,9,86,20,3,13,23.1,0,0,0.0,...,0,3,6,7,1.00,1.00,University of Kansas,4,195.0,SF
486,Zach LaVine,77,1902,778,286,677,42.2,57,167,34.1,...,10,193,158,720,1.43,0.28,"University of California, Los Angeles",0,192.5,PG
487,Zach Randolph,71,2304,1143,454,932,48.7,7,20,35.0,...,14,156,175,1422,0.98,0.44,Michigan State University,13,202.5,PF
488,Zaza Pachulia,73,1730,606,240,529,45.4,0,3,0.0,...,21,133,170,929,1.34,0.60,NaN,11,207.5,C
489,Zoran Dragic,16,75,28,11,30,36.7,3,14,21.4,...,0,5,6,17,1.00,0.40,NaN,0,192.5,SG

In [38]:
def load_and_process(url_or_path_to_csv_file):

    df = (pd.read_csv(url_or_path_to_csv_file)
          .drop(columns = ['BMI','Weight','Team','Birth_Place','Birthdate','Age'])
          .dropna()     
)
load_and_process('../../data/raw/players_stats.csv')
df

,Name,Games Played,MIN,PTS,FGM,FGA,FG%,3PM,3PA,3P%,...,BLK,TOV,PF,EFF,AST/TOV,STL/TOV,Collage,Experience,Height,Pos
0,AJ Price,26,324,133,51,137,37.2,15,57,26.3,...,0,14,15,110,3.29,0.50,University of Connecticut,5,185.0,PG
1,Aaron Brooks,82,1885,954,344,817,42.1,121,313,38.7,...,15,157,189,791,1.66,0.34,University of Oregon,6,180.0,PG
2,Aaron Gordon,47,797,243,93,208,44.7,13,48,27.1,...,22,38,83,318,0.87,0.55,University of Arizona,R,202.5,PF
3,Adreian Payne,32,740,213,91,220,41.4,1,9,11.1,...,9,44,88,244,0.68,0.43,Michigan State University,R,205.0,PF
4,Al Horford,76,2318,1156,519,965,53.8,11,36,30.6,...,98,100,121,1530,2.44,0.68,University of Florida,7,205.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,Willie Green,52,951,306,118,306,38.6,42,121,34.7,...,5,48,81,242,1.42,0.54,University of Detroit Mercy,11,190.0,SG
484,Wilson Chandler,78,2471,1085,418,975,42.9,139,406,34.2,...,29,110,231,1082,1.22,0.53,DePaul University,7,200.0,SF
485,Xavier Henry,9,86,20,3,13,23.1,0,0,0.0,...,0,3,6,7,1.00,1.00,University of Kansas,4,195.0,SF
486,Zach LaVine,77,1902,778,286,677,42.2,57,167,34.1,...,10,193,158,720,1.43,0.28,"University of California, Los Angeles",R,192.5,PG
487,Zach Randolph,71,2304,1143,454,932,48.7,7,20,35.0,...,14,156,175,1422,0.98,0.44,Michigan State University,13,202.5,PF